package com.cymmetrik.webservices.hr;


import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-07-21T16:10:51.938+08:00
 * Generated source version: 2.7.15
 * 
 */
@WebServiceClient(name = "HRManagerService", 
                  wsdlLocation = "http://192.168.4.162:9000/HRManager?wsdl",
                  targetNamespace = "http://HR.WebService/") 
public class HRManagerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://HR.WebService/", "HRManagerService");
    public final static QName HRManagerPort = new QName("http://HR.WebService/", "HRManagerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.4.162:9000/HRManager?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HRManagerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.4.162:9000/HRManager?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HRManagerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HRManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HRManagerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HRManagerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HRManagerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HRManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IHRService
     */
    @WebEndpoint(name = "HRManagerPort")
    public IHRService getHRManagerPort() {
        return super.getPort(HRManagerPort, IHRService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHRService
     */
    @WebEndpoint(name = "HRManagerPort")
    public IHRService getHRManagerPort(WebServiceFeature... features) {
        return super.getPort(HRManagerPort, IHRService.class, features);
    }

}
