
package snc02ManagerWebService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-07-20T08:30:33.550+08:00
 * Generated source version: 2.7.15
 * 
 */
public final class ISNC02Manager_SNC02ManagerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://WebService/", "SNC02ManagerService");

    private ISNC02Manager_SNC02ManagerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SNC02ManagerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SNC02ManagerService ss = new SNC02ManagerService(wsdlURL, SERVICE_NAME);
        ISNC02Manager port = ss.getSNC02ManagerPort();  
        
        {
        System.out.println("Invoking saveSNC02...");
        snc02ManagerWebService.Snc02 _saveSNC02_snc = new snc02ManagerWebService.Snc02();
        _saveSNC02_snc.setSncx0201("Sncx0201-103373289");
        _saveSNC02_snc.setSncx0202("Sncx02021172772528");
        _saveSNC02_snc.setSncx0203(0.8612388f);
        _saveSNC02_snc.setSncx0204("Sncx0204661087208");
        boolean _saveSNC02__return = port.saveSNC02(_saveSNC02_snc);
        System.out.println("saveSNC02.result=" + _saveSNC02__return);


        }
        {
        System.out.println("Invoking getRecentSNCX02S...");
        java.lang.String _getRecentSNCX02S_strCompanyId = "_getRecentSNCX02S_strCompanyId-1962886968";
        java.util.List<snc02ManagerWebService.Snc02> _getRecentSNCX02S__return = port.getRecentSNCX02S(_getRecentSNCX02S_strCompanyId);
        System.out.println("getRecentSNCX02S.result=" + _getRecentSNCX02S__return);


        }

        System.exit(0);
    }

}
