package com.cymmetrik.webservices.hr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-31T11:43:13.250+08:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://HR.WebService/", name = "IHRService")
@XmlSeeAlso({ObjectFactory.class})
public interface IHRService {

    @WebMethod
    @RequestWrapper(localName = "getDeptsByCompNoDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDeptsByCompNoDeptNo")
    @ResponseWrapper(localName = "getDeptsByCompNoDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDeptsByCompNoDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Department> getDeptsByCompNoDeptNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo,
        @WebParam(name = "strCriteria", targetNamespace = "")
        java.lang.String strCriteria
    );

    @WebMethod
    @RequestWrapper(localName = "getAllUnderEmpsNoByCompNoDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllUnderEmpsNoByCompNoDeptNo")
    @ResponseWrapper(localName = "getAllUnderEmpsNoByCompNoDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllUnderEmpsNoByCompNoDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getAllUnderEmpsNoByCompNoDeptNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo
    );

    @WebMethod
    @RequestWrapper(localName = "getDeptsByUpperDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDeptsByUpperDeptNo")
    @ResponseWrapper(localName = "getDeptsByUpperDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDeptsByUpperDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Department> getDeptsByUpperDeptNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo
    );

    @WebMethod
    @RequestWrapper(localName = "getEmployeeByEmpNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetEmployeeByEmpNo")
    @ResponseWrapper(localName = "getEmployeeByEmpNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetEmployeeByEmpNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getEmployeeByEmpNo(
        @WebParam(name = "strEmpNo", targetNamespace = "")
        java.lang.String strEmpNo
    );

    @WebMethod
    @RequestWrapper(localName = "getDepartmentsByCompanyNoDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDepartmentsByCompanyNoDeptNo")
    @ResponseWrapper(localName = "getDepartmentsByCompanyNoDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDepartmentsByCompanyNoDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Department> getDepartmentsByCompanyNoDeptNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo,
        @WebParam(name = "strCriteria", targetNamespace = "")
        java.lang.String strCriteria
    );

    @WebMethod
    @RequestWrapper(localName = "getDeptsByDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDeptsByDeptNo")
    @ResponseWrapper(localName = "getDeptsByDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDeptsByDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Department> getDeptsByDeptNo(
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo
    );

    @WebMethod
    @RequestWrapper(localName = "getAllUnderEmployeesByCompanyNoDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllUnderEmployeesByCompanyNoDeptNo")
    @ResponseWrapper(localName = "getAllUnderEmployeesByCompanyNoDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllUnderEmployeesByCompanyNoDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getAllUnderEmployeesByCompanyNoDeptNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo,
        @WebParam(name = "strCriteria", targetNamespace = "")
        java.lang.String strCriteria
    );

    @WebMethod
    @RequestWrapper(localName = "getEmployeesByCompanyNoAndDeptNoAndJobStatus", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetEmployeesByCompanyNoAndDeptNoAndJobStatus")
    @ResponseWrapper(localName = "getEmployeesByCompanyNoAndDeptNoAndJobStatusResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetEmployeesByCompanyNoAndDeptNoAndJobStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getEmployeesByCompanyNoAndDeptNoAndJobStatus(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo,
        @WebParam(name = "bAll", targetNamespace = "")
        boolean bAll,
        @WebParam(name = "jobStatus", targetNamespace = "")
        int jobStatus
    );

    @WebMethod
    @RequestWrapper(localName = "getUpperDeptsByCompNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetUpperDeptsByCompNo")
    @ResponseWrapper(localName = "getUpperDeptsByCompNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetUpperDeptsByCompNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Department> getUpperDeptsByCompNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo
    );

    @WebMethod
    @RequestWrapper(localName = "getEmployeeByEmpName", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetEmployeeByEmpName")
    @ResponseWrapper(localName = "getEmployeeByEmpNameResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetEmployeeByEmpNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getEmployeeByEmpName(
        @WebParam(name = "strEmpName", targetNamespace = "")
        java.lang.String strEmpName
    );

    @WebMethod
    @RequestWrapper(localName = "getAllUnderDeptsNoByCompNoDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllUnderDeptsNoByCompNoDeptNo")
    @ResponseWrapper(localName = "getAllUnderDeptsNoByCompNoDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllUnderDeptsNoByCompNoDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getAllUnderDeptsNoByCompNoDeptNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo
    );

    @WebMethod
    @RequestWrapper(localName = "getAllUnderEmployeesByCompanyNoDeptNoMainCompY", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllUnderEmployeesByCompanyNoDeptNoMainCompY")
    @ResponseWrapper(localName = "getAllUnderEmployeesByCompanyNoDeptNoMainCompYResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllUnderEmployeesByCompanyNoDeptNoMainCompYResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getAllUnderEmployeesByCompanyNoDeptNoMainCompY(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo,
        @WebParam(name = "strCriteria", targetNamespace = "")
        java.lang.String strCriteria
    );

    @WebMethod
    @RequestWrapper(localName = "getEmployeesByCompanyNoAndDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetEmployeesByCompanyNoAndDeptNo")
    @ResponseWrapper(localName = "getEmployeesByCompanyNoAndDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetEmployeesByCompanyNoAndDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getEmployeesByCompanyNoAndDeptNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo,
        @WebParam(name = "bAll", targetNamespace = "")
        boolean bAll
    );

    @WebMethod
    @RequestWrapper(localName = "getDeptsNoByCompanyNoAndDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDeptsNoByCompanyNoAndDeptNo")
    @ResponseWrapper(localName = "getDeptsNoByCompanyNoAndDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDeptsNoByCompanyNoAndDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getDeptsNoByCompanyNoAndDeptNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo
    );

    @WebMethod
    @RequestWrapper(localName = "getDepartmentsByCompanyNoAndDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDepartmentsByCompanyNoAndDeptNo")
    @ResponseWrapper(localName = "getDepartmentsByCompanyNoAndDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetDepartmentsByCompanyNoAndDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Department> getDepartmentsByCompanyNoAndDeptNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo
    );

    @WebMethod
    @RequestWrapper(localName = "getAllCompany", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllCompany")
    @ResponseWrapper(localName = "getAllCompanyResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllCompanyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Company> getAllCompany();

    @WebMethod
    @RequestWrapper(localName = "getEmployeeByLikeNameLoginId", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetEmployeeByLikeNameLoginId")
    @ResponseWrapper(localName = "getEmployeeByLikeNameLoginIdResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetEmployeeByLikeNameLoginIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getEmployeeByLikeNameLoginId(
        @WebParam(name = "strData", targetNamespace = "")
        java.lang.String strData
    );

    @WebMethod
    @RequestWrapper(localName = "getAllEmployeesByCompanyNoAndDeptNo", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllEmployeesByCompanyNoAndDeptNo")
    @ResponseWrapper(localName = "getAllEmployeesByCompanyNoAndDeptNoResponse", targetNamespace = "http://HR.WebService/", className = "com.cymmetrik.webservices.hr.GetAllEmployeesByCompanyNoAndDeptNoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getAllEmployeesByCompanyNoAndDeptNo(
        @WebParam(name = "strCompanyNo", targetNamespace = "")
        java.lang.String strCompanyNo,
        @WebParam(name = "strDeptNo", targetNamespace = "")
        java.lang.String strDeptNo,
        @WebParam(name = "bAll", targetNamespace = "")
        boolean bAll
    );
}
