
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package snc02ManagerWebService;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-07-20T08:30:33.629+08:00
 * Generated source version: 2.7.15
 * 
 */

@javax.jws.WebService(
                      serviceName = "SNC02ManagerService",
                      portName = "SNC02ManagerPort",
                      targetNamespace = "http://WebService/",
                      wsdlLocation = "http://192.168.4.162:9092/SNC02Manager?wsdl",
                      endpointInterface = "snc02ManagerWebService.ISNC02Manager")
                      
public class ISNC02ManagerImpl implements ISNC02Manager {

    private static final Logger LOG = Logger.getLogger(ISNC02ManagerImpl.class.getName());

    /* (non-Javadoc)
     * @see snc02ManagerWebService.ISNC02Manager#saveSNC02(snc02ManagerWebService.Snc02  snc )*
     */
    public boolean saveSNC02(snc02ManagerWebService.Snc02 snc) { 
        LOG.info("Executing operation saveSNC02");
        System.out.println(snc);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see snc02ManagerWebService.ISNC02Manager#getRecentSNCX02S(java.lang.String  strCompanyId )*
     */
    public java.util.List<snc02ManagerWebService.Snc02> getRecentSNCX02S(java.lang.String strCompanyId) { 
        LOG.info("Executing operation getRecentSNCX02S");
        System.out.println(strCompanyId);
        try {
            java.util.List<snc02ManagerWebService.Snc02> _return = new java.util.ArrayList<snc02ManagerWebService.Snc02>();
            snc02ManagerWebService.Snc02 _returnVal1 = new snc02ManagerWebService.Snc02();
            _returnVal1.setSncx0201("Sncx0201370416555");
            _returnVal1.setSncx0202("Sncx0202-1799438764");
            _returnVal1.setSncx0203(0.74592656f);
            _returnVal1.setSncx0204("Sncx0204896119081");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
