
package com.cymmetrik.webservices.hr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-31T11:43:13.089+08:00
 * Generated source version: 2.7.16
 * 
 */
public final class IHRService_HRManagerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://HR.WebService/", "HRManagerService");

    private IHRService_HRManagerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HRManagerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HRManagerService ss = new HRManagerService(wsdlURL, SERVICE_NAME);
        IHRService port = ss.getHRManagerPort();  
        
        {
        System.out.println("Invoking getDeptsByCompNoDeptNo...");
        java.lang.String _getDeptsByCompNoDeptNo_strCompanyNo = "_getDeptsByCompNoDeptNo_strCompanyNo646616090";
        java.lang.String _getDeptsByCompNoDeptNo_strDeptNo = "_getDeptsByCompNoDeptNo_strDeptNo-1729021859";
        java.lang.String _getDeptsByCompNoDeptNo_strCriteria = "_getDeptsByCompNoDeptNo_strCriteria1355450582";
        java.util.List<com.cymmetrik.webservices.hr.Department> _getDeptsByCompNoDeptNo__return = port.getDeptsByCompNoDeptNo(_getDeptsByCompNoDeptNo_strCompanyNo, _getDeptsByCompNoDeptNo_strDeptNo, _getDeptsByCompNoDeptNo_strCriteria);
        System.out.println("getDeptsByCompNoDeptNo.result=" + _getDeptsByCompNoDeptNo__return);


        }
        {
        System.out.println("Invoking getAllUnderEmpsNoByCompNoDeptNo...");
        java.lang.String _getAllUnderEmpsNoByCompNoDeptNo_strCompanyNo = "_getAllUnderEmpsNoByCompNoDeptNo_strCompanyNo-641356045";
        java.lang.String _getAllUnderEmpsNoByCompNoDeptNo_strDeptNo = "_getAllUnderEmpsNoByCompNoDeptNo_strDeptNo305053434";
        int _getAllUnderEmpsNoByCompNoDeptNo__return = port.getAllUnderEmpsNoByCompNoDeptNo(_getAllUnderEmpsNoByCompNoDeptNo_strCompanyNo, _getAllUnderEmpsNoByCompNoDeptNo_strDeptNo);
        System.out.println("getAllUnderEmpsNoByCompNoDeptNo.result=" + _getAllUnderEmpsNoByCompNoDeptNo__return);


        }
        {
        System.out.println("Invoking getDeptsByUpperDeptNo...");
        java.lang.String _getDeptsByUpperDeptNo_strCompanyNo = "_getDeptsByUpperDeptNo_strCompanyNo1325059069";
        java.lang.String _getDeptsByUpperDeptNo_strDeptNo = "_getDeptsByUpperDeptNo_strDeptNo-1992686884";
        java.util.List<com.cymmetrik.webservices.hr.Department> _getDeptsByUpperDeptNo__return = port.getDeptsByUpperDeptNo(_getDeptsByUpperDeptNo_strCompanyNo, _getDeptsByUpperDeptNo_strDeptNo);
        System.out.println("getDeptsByUpperDeptNo.result=" + _getDeptsByUpperDeptNo__return);


        }
        {
        System.out.println("Invoking getEmployeeByEmpNo...");
        java.lang.String _getEmployeeByEmpNo_strEmpNo = "_getEmployeeByEmpNo_strEmpNo-1787933754";
        java.util.List<com.cymmetrik.webservices.hr.Employee> _getEmployeeByEmpNo__return = port.getEmployeeByEmpNo(_getEmployeeByEmpNo_strEmpNo);
        System.out.println("getEmployeeByEmpNo.result=" + _getEmployeeByEmpNo__return);


        }
        {
        System.out.println("Invoking getDepartmentsByCompanyNoDeptNo...");
        java.lang.String _getDepartmentsByCompanyNoDeptNo_strCompanyNo = "_getDepartmentsByCompanyNoDeptNo_strCompanyNo989608622";
        java.lang.String _getDepartmentsByCompanyNoDeptNo_strDeptNo = "_getDepartmentsByCompanyNoDeptNo_strDeptNo263080557";
        java.lang.String _getDepartmentsByCompanyNoDeptNo_strCriteria = "_getDepartmentsByCompanyNoDeptNo_strCriteria-952177701";
        java.util.List<com.cymmetrik.webservices.hr.Department> _getDepartmentsByCompanyNoDeptNo__return = port.getDepartmentsByCompanyNoDeptNo(_getDepartmentsByCompanyNoDeptNo_strCompanyNo, _getDepartmentsByCompanyNoDeptNo_strDeptNo, _getDepartmentsByCompanyNoDeptNo_strCriteria);
        System.out.println("getDepartmentsByCompanyNoDeptNo.result=" + _getDepartmentsByCompanyNoDeptNo__return);


        }
        {
        System.out.println("Invoking getDeptsByDeptNo...");
        java.lang.String _getDeptsByDeptNo_strDeptNo = "_getDeptsByDeptNo_strDeptNo-1927288178";
        java.util.List<com.cymmetrik.webservices.hr.Department> _getDeptsByDeptNo__return = port.getDeptsByDeptNo(_getDeptsByDeptNo_strDeptNo);
        System.out.println("getDeptsByDeptNo.result=" + _getDeptsByDeptNo__return);


        }
        {
        System.out.println("Invoking getAllUnderEmployeesByCompanyNoDeptNo...");
        java.lang.String _getAllUnderEmployeesByCompanyNoDeptNo_strCompanyNo = "_getAllUnderEmployeesByCompanyNoDeptNo_strCompanyNo646557878";
        java.lang.String _getAllUnderEmployeesByCompanyNoDeptNo_strDeptNo = "_getAllUnderEmployeesByCompanyNoDeptNo_strDeptNo-252151105";
        java.lang.String _getAllUnderEmployeesByCompanyNoDeptNo_strCriteria = "_getAllUnderEmployeesByCompanyNoDeptNo_strCriteria570113979";
        java.util.List<com.cymmetrik.webservices.hr.Employee> _getAllUnderEmployeesByCompanyNoDeptNo__return = port.getAllUnderEmployeesByCompanyNoDeptNo(_getAllUnderEmployeesByCompanyNoDeptNo_strCompanyNo, _getAllUnderEmployeesByCompanyNoDeptNo_strDeptNo, _getAllUnderEmployeesByCompanyNoDeptNo_strCriteria);
        System.out.println("getAllUnderEmployeesByCompanyNoDeptNo.result=" + _getAllUnderEmployeesByCompanyNoDeptNo__return);


        }
        {
        System.out.println("Invoking getEmployeesByCompanyNoAndDeptNoAndJobStatus...");
        java.lang.String _getEmployeesByCompanyNoAndDeptNoAndJobStatus_strCompanyNo = "_getEmployeesByCompanyNoAndDeptNoAndJobStatus_strCompanyNo-555715213";
        java.lang.String _getEmployeesByCompanyNoAndDeptNoAndJobStatus_strDeptNo = "_getEmployeesByCompanyNoAndDeptNoAndJobStatus_strDeptNo753007343";
        boolean _getEmployeesByCompanyNoAndDeptNoAndJobStatus_bAll = true;
        int _getEmployeesByCompanyNoAndDeptNoAndJobStatus_jobStatus = 1075082530;
        java.util.List<com.cymmetrik.webservices.hr.Employee> _getEmployeesByCompanyNoAndDeptNoAndJobStatus__return = port.getEmployeesByCompanyNoAndDeptNoAndJobStatus(_getEmployeesByCompanyNoAndDeptNoAndJobStatus_strCompanyNo, _getEmployeesByCompanyNoAndDeptNoAndJobStatus_strDeptNo, _getEmployeesByCompanyNoAndDeptNoAndJobStatus_bAll, _getEmployeesByCompanyNoAndDeptNoAndJobStatus_jobStatus);
        System.out.println("getEmployeesByCompanyNoAndDeptNoAndJobStatus.result=" + _getEmployeesByCompanyNoAndDeptNoAndJobStatus__return);


        }
        {
        System.out.println("Invoking getUpperDeptsByCompNo...");
        java.lang.String _getUpperDeptsByCompNo_strCompanyNo = "_getUpperDeptsByCompNo_strCompanyNo633859469";
        java.util.List<com.cymmetrik.webservices.hr.Department> _getUpperDeptsByCompNo__return = port.getUpperDeptsByCompNo(_getUpperDeptsByCompNo_strCompanyNo);
        System.out.println("getUpperDeptsByCompNo.result=" + _getUpperDeptsByCompNo__return);


        }
        {
        System.out.println("Invoking getEmployeeByEmpName...");
        java.lang.String _getEmployeeByEmpName_strEmpName = "_getEmployeeByEmpName_strEmpName645973029";
        java.util.List<com.cymmetrik.webservices.hr.Employee> _getEmployeeByEmpName__return = port.getEmployeeByEmpName(_getEmployeeByEmpName_strEmpName);
        System.out.println("getEmployeeByEmpName.result=" + _getEmployeeByEmpName__return);


        }
        {
        System.out.println("Invoking getAllUnderDeptsNoByCompNoDeptNo...");
        java.lang.String _getAllUnderDeptsNoByCompNoDeptNo_strCompanyNo = "_getAllUnderDeptsNoByCompNoDeptNo_strCompanyNo1446658148";
        java.lang.String _getAllUnderDeptsNoByCompNoDeptNo_strDeptNo = "_getAllUnderDeptsNoByCompNoDeptNo_strDeptNo-636018134";
        int _getAllUnderDeptsNoByCompNoDeptNo__return = port.getAllUnderDeptsNoByCompNoDeptNo(_getAllUnderDeptsNoByCompNoDeptNo_strCompanyNo, _getAllUnderDeptsNoByCompNoDeptNo_strDeptNo);
        System.out.println("getAllUnderDeptsNoByCompNoDeptNo.result=" + _getAllUnderDeptsNoByCompNoDeptNo__return);


        }
        {
        System.out.println("Invoking getAllUnderEmployeesByCompanyNoDeptNoMainCompY...");
        java.lang.String _getAllUnderEmployeesByCompanyNoDeptNoMainCompY_strCompanyNo = "_getAllUnderEmployeesByCompanyNoDeptNoMainCompY_strCompanyNo1918321542";
        java.lang.String _getAllUnderEmployeesByCompanyNoDeptNoMainCompY_strDeptNo = "_getAllUnderEmployeesByCompanyNoDeptNoMainCompY_strDeptNo522198508";
        java.lang.String _getAllUnderEmployeesByCompanyNoDeptNoMainCompY_strCriteria = "_getAllUnderEmployeesByCompanyNoDeptNoMainCompY_strCriteria-1755215821";
        java.util.List<com.cymmetrik.webservices.hr.Employee> _getAllUnderEmployeesByCompanyNoDeptNoMainCompY__return = port.getAllUnderEmployeesByCompanyNoDeptNoMainCompY(_getAllUnderEmployeesByCompanyNoDeptNoMainCompY_strCompanyNo, _getAllUnderEmployeesByCompanyNoDeptNoMainCompY_strDeptNo, _getAllUnderEmployeesByCompanyNoDeptNoMainCompY_strCriteria);
        System.out.println("getAllUnderEmployeesByCompanyNoDeptNoMainCompY.result=" + _getAllUnderEmployeesByCompanyNoDeptNoMainCompY__return);


        }
        {
        System.out.println("Invoking getEmployeesByCompanyNoAndDeptNo...");
        java.lang.String _getEmployeesByCompanyNoAndDeptNo_strCompanyNo = "_getEmployeesByCompanyNoAndDeptNo_strCompanyNo1478735956";
        java.lang.String _getEmployeesByCompanyNoAndDeptNo_strDeptNo = "_getEmployeesByCompanyNoAndDeptNo_strDeptNo2060555901";
        boolean _getEmployeesByCompanyNoAndDeptNo_bAll = true;
        java.util.List<com.cymmetrik.webservices.hr.Employee> _getEmployeesByCompanyNoAndDeptNo__return = port.getEmployeesByCompanyNoAndDeptNo(_getEmployeesByCompanyNoAndDeptNo_strCompanyNo, _getEmployeesByCompanyNoAndDeptNo_strDeptNo, _getEmployeesByCompanyNoAndDeptNo_bAll);
        System.out.println("getEmployeesByCompanyNoAndDeptNo.result=" + _getEmployeesByCompanyNoAndDeptNo__return);


        }
        {
        System.out.println("Invoking getDeptsNoByCompanyNoAndDeptNo...");
        java.lang.String _getDeptsNoByCompanyNoAndDeptNo_strCompanyNo = "_getDeptsNoByCompanyNoAndDeptNo_strCompanyNo2007227813";
        java.lang.String _getDeptsNoByCompanyNoAndDeptNo_strDeptNo = "_getDeptsNoByCompanyNoAndDeptNo_strDeptNo504794043";
        int _getDeptsNoByCompanyNoAndDeptNo__return = port.getDeptsNoByCompanyNoAndDeptNo(_getDeptsNoByCompanyNoAndDeptNo_strCompanyNo, _getDeptsNoByCompanyNoAndDeptNo_strDeptNo);
        System.out.println("getDeptsNoByCompanyNoAndDeptNo.result=" + _getDeptsNoByCompanyNoAndDeptNo__return);


        }
        {
        System.out.println("Invoking getDepartmentsByCompanyNoAndDeptNo...");
        java.lang.String _getDepartmentsByCompanyNoAndDeptNo_strCompanyNo = "_getDepartmentsByCompanyNoAndDeptNo_strCompanyNo-1162871507";
        java.lang.String _getDepartmentsByCompanyNoAndDeptNo_strDeptNo = "_getDepartmentsByCompanyNoAndDeptNo_strDeptNo-1641618679";
        java.util.List<com.cymmetrik.webservices.hr.Department> _getDepartmentsByCompanyNoAndDeptNo__return = port.getDepartmentsByCompanyNoAndDeptNo(_getDepartmentsByCompanyNoAndDeptNo_strCompanyNo, _getDepartmentsByCompanyNoAndDeptNo_strDeptNo);
        System.out.println("getDepartmentsByCompanyNoAndDeptNo.result=" + _getDepartmentsByCompanyNoAndDeptNo__return);


        }
        {
        System.out.println("Invoking getAllCompany...");
        java.util.List<com.cymmetrik.webservices.hr.Company> _getAllCompany__return = port.getAllCompany();
        System.out.println("getAllCompany.result=" + _getAllCompany__return);


        }
        {
        System.out.println("Invoking getEmployeeByLikeNameLoginId...");
        java.lang.String _getEmployeeByLikeNameLoginId_strData = "_getEmployeeByLikeNameLoginId_strData1034705020";
        java.util.List<com.cymmetrik.webservices.hr.Employee> _getEmployeeByLikeNameLoginId__return = port.getEmployeeByLikeNameLoginId(_getEmployeeByLikeNameLoginId_strData);
        System.out.println("getEmployeeByLikeNameLoginId.result=" + _getEmployeeByLikeNameLoginId__return);


        }
        {
        System.out.println("Invoking getAllEmployeesByCompanyNoAndDeptNo...");
        java.lang.String _getAllEmployeesByCompanyNoAndDeptNo_strCompanyNo = "_getAllEmployeesByCompanyNoAndDeptNo_strCompanyNo-573793908";
        java.lang.String _getAllEmployeesByCompanyNoAndDeptNo_strDeptNo = "_getAllEmployeesByCompanyNoAndDeptNo_strDeptNo-819577522";
        boolean _getAllEmployeesByCompanyNoAndDeptNo_bAll = false;
        java.util.List<com.cymmetrik.webservices.hr.Employee> _getAllEmployeesByCompanyNoAndDeptNo__return = port.getAllEmployeesByCompanyNoAndDeptNo(_getAllEmployeesByCompanyNoAndDeptNo_strCompanyNo, _getAllEmployeesByCompanyNoAndDeptNo_strDeptNo, _getAllEmployeesByCompanyNoAndDeptNo_bAll);
        System.out.println("getAllEmployeesByCompanyNoAndDeptNo.result=" + _getAllEmployeesByCompanyNoAndDeptNo__return);


        }

        System.exit(0);
    }

}
