package snc01ManagerWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-03T18:00:53.890+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://WebService/", name = "ISNC01Manager")
@XmlSeeAlso({ObjectFactory.class})
public interface ISNC01Manager {

    @WebMethod
    @RequestWrapper(localName = "getSNCX01ByMachineName", targetNamespace = "http://WebService/", className = "snc01ManagerWebService.GetSNCX01ByMachineName")
    @ResponseWrapper(localName = "getSNCX01ByMachineNameResponse", targetNamespace = "http://WebService/", className = "snc01ManagerWebService.GetSNCX01ByMachineNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public snc01ManagerWebService.Snc01 getSNCX01ByMachineName(
        @WebParam(name = "strMachineName", targetNamespace = "")
        java.lang.String strMachineName
    );

    @WebMethod(operationName = "getAllSNCX01s")
    @RequestWrapper(localName = "getAllSNCX01s", targetNamespace = "http://WebService/", className = "snc01ManagerWebService.GetAllSNCX01S")
    @ResponseWrapper(localName = "getAllSNCX01sResponse", targetNamespace = "http://WebService/", className = "snc01ManagerWebService.GetAllSNCX01SResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<snc01ManagerWebService.Snc01> getAllSNCX01S();

    @WebMethod(operationName = "SaveSNC01")
    @RequestWrapper(localName = "SaveSNC01", targetNamespace = "http://WebService/", className = "snc01ManagerWebService.SaveSNC01")
    @ResponseWrapper(localName = "SaveSNC01Response", targetNamespace = "http://WebService/", className = "snc01ManagerWebService.SaveSNC01Response")
    @WebResult(name = "return", targetNamespace = "")
    public boolean saveSNC01(
        @WebParam(name = "snc", targetNamespace = "")
        snc01ManagerWebService.Snc01 snc
    );

    @WebMethod(operationName = "getSNCX01sByMins")
    @RequestWrapper(localName = "getSNCX01sByMins", targetNamespace = "http://WebService/", className = "snc01ManagerWebService.GetSNCX01SByMins")
    @ResponseWrapper(localName = "getSNCX01sByMinsResponse", targetNamespace = "http://WebService/", className = "snc01ManagerWebService.GetSNCX01SByMinsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<snc01ManagerWebService.Snc01> getSNCX01SByMins(
        @WebParam(name = "snc", targetNamespace = "")
        snc01ManagerWebService.Snc01 snc
    );

    @WebMethod(operationName = "getSNCX01s")
    @RequestWrapper(localName = "getSNCX01s", targetNamespace = "http://WebService/", className = "snc01ManagerWebService.GetSNCX01S")
    @ResponseWrapper(localName = "getSNCX01sResponse", targetNamespace = "http://WebService/", className = "snc01ManagerWebService.GetSNCX01SResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<snc01ManagerWebService.Snc01> getSNCX01S(
        @WebParam(name = "snc", targetNamespace = "")
        snc01ManagerWebService.Snc01 snc
    );
}
