
package snc01ManagerWebService;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-03T18:00:53.847+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class ISNC01Manager_SNC01ManagerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://WebService/", "SNC01ManagerService");

    private ISNC01Manager_SNC01ManagerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SNC01ManagerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SNC01ManagerService ss = new SNC01ManagerService(wsdlURL, SERVICE_NAME);
        ISNC01Manager port = ss.getSNC01ManagerPort();  
        
        {
        System.out.println("Invoking getSNCX01ByMachineName...");
        java.lang.String _getSNCX01ByMachineName_strMachineName = "_getSNCX01ByMachineName_strMachineName327000654";
        snc01ManagerWebService.Snc01 _getSNCX01ByMachineName__return = port.getSNCX01ByMachineName(_getSNCX01ByMachineName_strMachineName);
        System.out.println("getSNCX01ByMachineName.result=" + _getSNCX01ByMachineName__return);


        }
        {
        System.out.println("Invoking getAllSNCX01S...");
        java.util.List<snc01ManagerWebService.Snc01> _getAllSNCX01S__return = port.getAllSNCX01S();
        System.out.println("getAllSNCX01S.result=" + _getAllSNCX01S__return);


        }
        {
        System.out.println("Invoking saveSNC01...");
        snc01ManagerWebService.Snc01 _saveSNC01_snc = new snc01ManagerWebService.Snc01();
        _saveSNC01_snc.setCompanyId("CompanyId-549282828");
        _saveSNC01_snc.setEnable("Enable-185412944");
        _saveSNC01_snc.setIp("Ip11754272");
        _saveSNC01_snc.setMac("Mac1489975856");
        _saveSNC01_snc.setMachineName("MachineName-2138076400");
        _saveSNC01_snc.setMemo("Memo72280169");
        _saveSNC01_snc.setMins("Mins682601320");
        boolean _saveSNC01__return = port.saveSNC01(_saveSNC01_snc);
        System.out.println("saveSNC01.result=" + _saveSNC01__return);


        }
        {
        System.out.println("Invoking getSNCX01SByMins...");
        snc01ManagerWebService.Snc01 _getSNCX01SByMins_snc = new snc01ManagerWebService.Snc01();
        _getSNCX01SByMins_snc.setCompanyId("CompanyId1049804860");
        _getSNCX01SByMins_snc.setEnable("Enable-1327091237");
        _getSNCX01SByMins_snc.setIp("Ip-97214835");
        _getSNCX01SByMins_snc.setMac("Mac-1124623953");
        _getSNCX01SByMins_snc.setMachineName("MachineName-1718985374");
        _getSNCX01SByMins_snc.setMemo("Memo121623897");
        _getSNCX01SByMins_snc.setMins("Mins396209004");
        java.util.List<snc01ManagerWebService.Snc01> _getSNCX01SByMins__return = port.getSNCX01SByMins(_getSNCX01SByMins_snc);
        System.out.println("getSNCX01SByMins.result=" + _getSNCX01SByMins__return);


        }
        {
        System.out.println("Invoking getSNCX01S...");
        snc01ManagerWebService.Snc01 _getSNCX01S_snc = new snc01ManagerWebService.Snc01();
        _getSNCX01S_snc.setCompanyId("CompanyId-752214012");
        _getSNCX01S_snc.setEnable("Enable-990218751");
        _getSNCX01S_snc.setIp("Ip110171647");
        _getSNCX01S_snc.setMac("Mac-1382517746");
        _getSNCX01S_snc.setMachineName("MachineName134817383");
        _getSNCX01S_snc.setMemo("Memo-1785836916");
        _getSNCX01S_snc.setMins("Mins1084599688");
        java.util.List<snc01ManagerWebService.Snc01> _getSNCX01S__return = port.getSNCX01S(_getSNCX01S_snc);
        System.out.println("getSNCX01S.result=" + _getSNCX01S__return);


        }

        System.exit(0);
    }

}
