package com.cymmetrik.webservices.hr;





/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

/**
 * This class was generated by Apache CXF 2.6.5 2012-06-07T14:42:23.108+08:00
 * Generated source version: 2.6.5 Modified by Shihwen Wei
 */
public final class HRManager {

	public static List<Company> getAllCompany(String strWsdlPath) {
		
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Company> lstCompany = port.getAllCompany();

		return lstCompany;
	}
	
	public static List<Department> getDepartmentsByCompanyNoDeptNo(String strWsdlPath, String strComp, String strDept, String strCriteria) 
	{
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Department> lstDepartment = port.getDepartmentsByCompanyNoDeptNo(strComp, strDept, strCriteria);
		return lstDepartment;
	}

	public static List<Employee> getEmployeesByCompanyNoAndDeptNo(String strWsdlPath, String strComp, String strDept, boolean bAll) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Employee> lstEmployee = port.getEmployeesByCompanyNoAndDeptNo(strComp, strDept, bAll);
		return lstEmployee;
	}

	public static List<Employee> getEmployeesByCompanyNoAndDeptNoAndJobStatus(String strWsdlPath, String strComp, String strDept, boolean bAll,int iJobStatus) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Employee> lstEmployee = port.getEmployeesByCompanyNoAndDeptNoAndJobStatus(strComp, strDept, bAll, iJobStatus);
		return lstEmployee;
	}

	public static List<Employee> getEmployeeByEmpNo(String strWsdlPath, String strEmpNo) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Employee> lstEmployee = port.getEmployeeByEmpNo(strEmpNo);
		return lstEmployee;
	}
	
	public static List<Employee> getEmployeeByEmpName(String strWsdlPath, String strEmpName) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Employee> lstEmployee = port.getEmployeeByEmpName(strEmpName);
		return lstEmployee;
	}
	
	public static List<Department> getDeptsByDeptNo(String strWsdlPath, String strDeptNo) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Department> lstDepartment = port.getDeptsByDeptNo(strDeptNo);
		return lstDepartment;
	}
	
	public static List<Department> getDeptsByUpperDeptNo(String strWsdlPath, String strCompNo, String strDeptNo) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Department> lstDepartment = port.getDeptsByUpperDeptNo(strCompNo, strDeptNo);
		return lstDepartment;
	}
	
	public static List<Department> getDeptsByCompNoDeptNo(String strWsdlPath, String strCompNo, String strDeptNo, String strCriteria) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Department> lstDepartment = port.getDeptsByCompNoDeptNo(strCompNo, strDeptNo, strCriteria);
		return lstDepartment;
	}
	
	public static List<Employee> getAllUnderEmployeesByCompNoDeptNo(String strWsdlPath, String strCompNo, String strDeptNo, String strCriteria) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Employee> lstEmployee = port.getAllUnderEmployeesByCompanyNoDeptNo(strCompNo, strDeptNo, strCriteria);
		return lstEmployee;
	}
	
	public static int getAllUnderEmpsNoByCompNoDeptNo(String strWsdlPath, String strCompNo, String strDeptNo) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}		
		IHRService port = service.getHRManagerPort();
		int iEmpNo = port.getAllUnderEmpsNoByCompNoDeptNo(strCompNo, strDeptNo);
		return iEmpNo;
	}
	
	public static int getDeptsNoByCompanyNoAndDeptNo(String strWsdlPath, String strCompNo, String strDeptNo) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		int iDeptNo = port.getDeptsNoByCompanyNoAndDeptNo(strCompNo, strDeptNo);
		return iDeptNo;
	}
	
	public static List<Department> getUpperDeptByCompNo(String strURL, String strWsdlPath, String strCompNo) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}		
		IHRService port = service.getHRManagerPort();
		List<Department> lstDepartment = port.getUpperDeptsByCompNo(strCompNo);
		return lstDepartment;
	}
	
	public static List<Employee> getEmployeeByLikeNameLoginId(String strWsdlPath, String strNameLoginId) {
		HRManagerService service=null;
		try {
			service = new HRManagerService(new URL(strWsdlPath));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		IHRService port = service.getHRManagerPort();
		List<Employee> lstEmployee = port.getEmployeeByLikeNameLoginId(strNameLoginId);
		return lstEmployee;
	}
	
}
