
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package snc01ManagerWebService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-03T18:00:53.881+08:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "SNC01ManagerService",
                      portName = "SNC01ManagerPort",
                      targetNamespace = "http://WebService/",
                      wsdlLocation = "http://192.168.4.162:9092/SNC01Manager?wsdl",
                      endpointInterface = "snc01ManagerWebService.ISNC01Manager")
                      
public class ISNC01ManagerImpl implements ISNC01Manager {

    private static final Logger LOG = Logger.getLogger(ISNC01ManagerImpl.class.getName());

    /* (non-Javadoc)
     * @see snc01ManagerWebService.ISNC01Manager#getSNCX01ByMachineName(java.lang.String  strMachineName )*
     */
    public snc01ManagerWebService.Snc01 getSNCX01ByMachineName(java.lang.String strMachineName) { 
        LOG.info("Executing operation getSNCX01ByMachineName");
        System.out.println(strMachineName);
        try {
            snc01ManagerWebService.Snc01 _return = new snc01ManagerWebService.Snc01();
            _return.setCompanyId("CompanyId953440120");
            _return.setEnable("Enable-1601919293");
            _return.setIp("Ip710114921");
            _return.setMac("Mac1587131912");
            _return.setMachineName("MachineName-779032018");
            _return.setMemo("Memo2009046043");
            _return.setMins("Mins1336715548");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see snc01ManagerWebService.ISNC01Manager#getAllSNCX01S(*
     */
    public java.util.List<snc01ManagerWebService.Snc01> getAllSNCX01S() { 
        LOG.info("Executing operation getAllSNCX01S");
        try {
            java.util.List<snc01ManagerWebService.Snc01> _return = new java.util.ArrayList<snc01ManagerWebService.Snc01>();
            snc01ManagerWebService.Snc01 _returnVal1 = new snc01ManagerWebService.Snc01();
            _returnVal1.setCompanyId("CompanyId901238337");
            _returnVal1.setEnable("Enable-129571335");
            _returnVal1.setIp("Ip-350736124");
            _returnVal1.setMac("Mac-1015458396");
            _returnVal1.setMachineName("MachineName-467357900");
            _returnVal1.setMemo("Memo797561322");
            _returnVal1.setMins("Mins2011160915");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see snc01ManagerWebService.ISNC01Manager#saveSNC01(snc01ManagerWebService.Snc01  snc )*
     */
    public boolean saveSNC01(snc01ManagerWebService.Snc01 snc) { 
        LOG.info("Executing operation saveSNC01");
        System.out.println(snc);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see snc01ManagerWebService.ISNC01Manager#getSNCX01SByMins(snc01ManagerWebService.Snc01  snc )*
     */
    public java.util.List<snc01ManagerWebService.Snc01> getSNCX01SByMins(snc01ManagerWebService.Snc01 snc) { 
        LOG.info("Executing operation getSNCX01SByMins");
        System.out.println(snc);
        try {
            java.util.List<snc01ManagerWebService.Snc01> _return = new java.util.ArrayList<snc01ManagerWebService.Snc01>();
            snc01ManagerWebService.Snc01 _returnVal1 = new snc01ManagerWebService.Snc01();
            _returnVal1.setCompanyId("CompanyId-432666885");
            _returnVal1.setEnable("Enable-1374837090");
            _returnVal1.setIp("Ip492310");
            _returnVal1.setMac("Mac-1448246842");
            _returnVal1.setMachineName("MachineName-455365419");
            _returnVal1.setMemo("Memo548139714");
            _returnVal1.setMins("Mins651061959");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see snc01ManagerWebService.ISNC01Manager#getSNCX01S(snc01ManagerWebService.Snc01  snc )*
     */
    public java.util.List<snc01ManagerWebService.Snc01> getSNCX01S(snc01ManagerWebService.Snc01 snc) { 
        LOG.info("Executing operation getSNCX01S");
        System.out.println(snc);
        try {
            java.util.List<snc01ManagerWebService.Snc01> _return = new java.util.ArrayList<snc01ManagerWebService.Snc01>();
            snc01ManagerWebService.Snc01 _returnVal1 = new snc01ManagerWebService.Snc01();
            _returnVal1.setCompanyId("CompanyId1226140380");
            _returnVal1.setEnable("Enable-1268809086");
            _returnVal1.setIp("Ip402146265");
            _returnVal1.setMac("Mac-607969602");
            _returnVal1.setMachineName("MachineName-1317967032");
            _returnVal1.setMemo("Memo976328401");
            _returnVal1.setMins("Mins2141968188");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
