
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cymmetrik.webservices.hr;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-31T11:43:13.202+08:00
 * Generated source version: 2.7.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "HRManagerService",
                      portName = "HRManagerPort",
                      targetNamespace = "http://HR.WebService/",
                      wsdlLocation = "http://192.168.4.162:9000/HRManager?wsdl",
                      endpointInterface = "com.cymmetrik.webservices.hr.IHRService")
                      
public class IHRServiceImpl implements IHRService {

    private static final Logger LOG = Logger.getLogger(IHRServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getDeptsByCompNoDeptNo(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo ,)java.lang.String  strCriteria )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Department> getDeptsByCompNoDeptNo(java.lang.String strCompanyNo,java.lang.String strDeptNo,java.lang.String strCriteria) { 
        LOG.info("Executing operation getDeptsByCompNoDeptNo");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        System.out.println(strCriteria);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Department> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Department>();
            com.cymmetrik.webservices.hr.Department _returnVal1 = new com.cymmetrik.webservices.hr.Department();
            _returnVal1.setDeptDeputyMgr1("DeptDeputyMgr1-1260010176");
            _returnVal1.setDeptDeputyMgr2("DeptDeputyMgr2-1689665099");
            _returnVal1.setDeptMgr("DeptMgr-583985861");
            _returnVal1.setDeptMgrName("DeptMgrName-2053933443");
            _returnVal1.setDeptName("DeptName-2051587705");
            _returnVal1.setDeptNo("DeptNo-1180932132");
            _returnVal1.setDeptOrderBy("DeptOrderBy-1978860588");
            _returnVal1.setDeptLevel("DeptLevel1984089377");
            _returnVal1.setDeptLevelDesc("DeptLevelDesc121100406");
            _returnVal1.setEffectDt("EffectDt1688579986");
            _returnVal1.setLevel("Level-2088863067");
            _returnVal1.setSegSegmentNo("SegSegmentNo-1282852907");
            _returnVal1.setUpperDept("UpperDept367059847");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getAllUnderEmpsNoByCompNoDeptNo(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo )*
     */
    public int getAllUnderEmpsNoByCompNoDeptNo(java.lang.String strCompanyNo,java.lang.String strDeptNo) { 
        LOG.info("Executing operation getAllUnderEmpsNoByCompNoDeptNo");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        try {
            int _return = 1789708232;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getDeptsByUpperDeptNo(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Department> getDeptsByUpperDeptNo(java.lang.String strCompanyNo,java.lang.String strDeptNo) { 
        LOG.info("Executing operation getDeptsByUpperDeptNo");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Department> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Department>();
            com.cymmetrik.webservices.hr.Department _returnVal1 = new com.cymmetrik.webservices.hr.Department();
            _returnVal1.setDeptDeputyMgr1("DeptDeputyMgr1-1606187449");
            _returnVal1.setDeptDeputyMgr2("DeptDeputyMgr2-869672000");
            _returnVal1.setDeptMgr("DeptMgr1157575564");
            _returnVal1.setDeptMgrName("DeptMgrName1008138625");
            _returnVal1.setDeptName("DeptName-996706042");
            _returnVal1.setDeptNo("DeptNo1249726575");
            _returnVal1.setDeptOrderBy("DeptOrderBy236930547");
            _returnVal1.setDeptLevel("DeptLevel1728409033");
            _returnVal1.setDeptLevelDesc("DeptLevelDesc1495897027");
            _returnVal1.setEffectDt("EffectDt1566791913");
            _returnVal1.setLevel("Level-491713974");
            _returnVal1.setSegSegmentNo("SegSegmentNo-885727515");
            _returnVal1.setUpperDept("UpperDept-830461668");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getEmployeeByEmpNo(java.lang.String  strEmpNo )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getEmployeeByEmpNo(java.lang.String strEmpNo) { 
        LOG.info("Executing operation getEmployeeByEmpNo");
        System.out.println(strEmpNo);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Employee> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Employee>();
            com.cymmetrik.webservices.hr.Employee _returnVal1 = new com.cymmetrik.webservices.hr.Employee();
            _returnVal1.setCardNo("CardNo-546399744");
            _returnVal1.setCompId("CompId1826880517");
            _returnVal1.setDeptName("DeptName-1349867317");
            _returnVal1.setDeptNo("DeptNo1237374665");
            _returnVal1.setEffectDt("EffectDt1810162153");
            _returnVal1.setEmail("Email361010303");
            _returnVal1.setEmpName("EmpName1232989396");
            _returnVal1.setEmpNo("EmpNo-998739640");
            _returnVal1.setJobCate("JobCate-138160881");
            _returnVal1.setJobCateDesc("JobCateDesc-1984931522");
            _returnVal1.setJobPlace("JobPlace-1908228945");
            _returnVal1.setJobPlaceDesc("JobPlaceDesc360940988");
            _returnVal1.setJobStatus(-140307421);
            _returnVal1.setSex("Sex2093353595");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getDepartmentsByCompanyNoDeptNo(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo ,)java.lang.String  strCriteria )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Department> getDepartmentsByCompanyNoDeptNo(java.lang.String strCompanyNo,java.lang.String strDeptNo,java.lang.String strCriteria) { 
        LOG.info("Executing operation getDepartmentsByCompanyNoDeptNo");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        System.out.println(strCriteria);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Department> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Department>();
            com.cymmetrik.webservices.hr.Department _returnVal1 = new com.cymmetrik.webservices.hr.Department();
            _returnVal1.setDeptDeputyMgr1("DeptDeputyMgr1-376930152");
            _returnVal1.setDeptDeputyMgr2("DeptDeputyMgr2534943250");
            _returnVal1.setDeptMgr("DeptMgr-1488310409");
            _returnVal1.setDeptMgrName("DeptMgrName88847840");
            _returnVal1.setDeptName("DeptName-990114614");
            _returnVal1.setDeptNo("DeptNo-1017941147");
            _returnVal1.setDeptOrderBy("DeptOrderBy1315044236");
            _returnVal1.setDeptLevel("DeptLevel2128392595");
            _returnVal1.setDeptLevelDesc("DeptLevelDesc1775311410");
            _returnVal1.setEffectDt("EffectDt-1002743133");
            _returnVal1.setLevel("Level-200402199");
            _returnVal1.setSegSegmentNo("SegSegmentNo-607272077");
            _returnVal1.setUpperDept("UpperDept1771968100");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getDeptsByDeptNo(java.lang.String  strDeptNo )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Department> getDeptsByDeptNo(java.lang.String strDeptNo) { 
        LOG.info("Executing operation getDeptsByDeptNo");
        System.out.println(strDeptNo);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Department> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Department>();
            com.cymmetrik.webservices.hr.Department _returnVal1 = new com.cymmetrik.webservices.hr.Department();
            _returnVal1.setDeptDeputyMgr1("DeptDeputyMgr1990099312");
            _returnVal1.setDeptDeputyMgr2("DeptDeputyMgr2-2102079186");
            _returnVal1.setDeptMgr("DeptMgr1465252000");
            _returnVal1.setDeptMgrName("DeptMgrName1360035538");
            _returnVal1.setDeptName("DeptName-523914934");
            _returnVal1.setDeptNo("DeptNo-485985432");
            _returnVal1.setDeptOrderBy("DeptOrderBy-655429312");
            _returnVal1.setDeptLevel("DeptLevel1286552378");
            _returnVal1.setDeptLevelDesc("DeptLevelDesc-834738451");
            _returnVal1.setEffectDt("EffectDt-1564014171");
            _returnVal1.setLevel("Level1804051584");
            _returnVal1.setSegSegmentNo("SegSegmentNo-1320965280");
            _returnVal1.setUpperDept("UpperDept-1395917832");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getAllUnderEmployeesByCompanyNoDeptNo(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo ,)java.lang.String  strCriteria )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getAllUnderEmployeesByCompanyNoDeptNo(java.lang.String strCompanyNo,java.lang.String strDeptNo,java.lang.String strCriteria) { 
        LOG.info("Executing operation getAllUnderEmployeesByCompanyNoDeptNo");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        System.out.println(strCriteria);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Employee> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Employee>();
            com.cymmetrik.webservices.hr.Employee _returnVal1 = new com.cymmetrik.webservices.hr.Employee();
            _returnVal1.setCardNo("CardNo-1244006965");
            _returnVal1.setCompId("CompId-1957633831");
            _returnVal1.setDeptName("DeptName232348669");
            _returnVal1.setDeptNo("DeptNo-2050237232");
            _returnVal1.setEffectDt("EffectDt1086895013");
            _returnVal1.setEmail("Email-610595692");
            _returnVal1.setEmpName("EmpName-942696713");
            _returnVal1.setEmpNo("EmpNo93904067");
            _returnVal1.setJobCate("JobCate-284228034");
            _returnVal1.setJobCateDesc("JobCateDesc-139400561");
            _returnVal1.setJobPlace("JobPlace-243842351");
            _returnVal1.setJobPlaceDesc("JobPlaceDesc1249055344");
            _returnVal1.setJobStatus(-2145900942);
            _returnVal1.setSex("Sex1846765377");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getEmployeesByCompanyNoAndDeptNoAndJobStatus(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo ,)boolean  bAll ,)int  jobStatus )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getEmployeesByCompanyNoAndDeptNoAndJobStatus(java.lang.String strCompanyNo,java.lang.String strDeptNo,boolean bAll,int jobStatus) { 
        LOG.info("Executing operation getEmployeesByCompanyNoAndDeptNoAndJobStatus");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        System.out.println(bAll);
        System.out.println(jobStatus);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Employee> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Employee>();
            com.cymmetrik.webservices.hr.Employee _returnVal1 = new com.cymmetrik.webservices.hr.Employee();
            _returnVal1.setCardNo("CardNo1953154404");
            _returnVal1.setCompId("CompId-141978009");
            _returnVal1.setDeptName("DeptName665175745");
            _returnVal1.setDeptNo("DeptNo-1187597830");
            _returnVal1.setEffectDt("EffectDt561307087");
            _returnVal1.setEmail("Email-419002356");
            _returnVal1.setEmpName("EmpName1669529702");
            _returnVal1.setEmpNo("EmpNo-467589521");
            _returnVal1.setJobCate("JobCate1270262187");
            _returnVal1.setJobCateDesc("JobCateDesc1172044992");
            _returnVal1.setJobPlace("JobPlace-1647280729");
            _returnVal1.setJobPlaceDesc("JobPlaceDesc-263140746");
            _returnVal1.setJobStatus(1124878723);
            _returnVal1.setSex("Sex1330527553");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getUpperDeptsByCompNo(java.lang.String  strCompanyNo )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Department> getUpperDeptsByCompNo(java.lang.String strCompanyNo) { 
        LOG.info("Executing operation getUpperDeptsByCompNo");
        System.out.println(strCompanyNo);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Department> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Department>();
            com.cymmetrik.webservices.hr.Department _returnVal1 = new com.cymmetrik.webservices.hr.Department();
            _returnVal1.setDeptDeputyMgr1("DeptDeputyMgr1-1976011410");
            _returnVal1.setDeptDeputyMgr2("DeptDeputyMgr22102682637");
            _returnVal1.setDeptMgr("DeptMgr-38610814");
            _returnVal1.setDeptMgrName("DeptMgrName387577169");
            _returnVal1.setDeptName("DeptName-1439806439");
            _returnVal1.setDeptNo("DeptNo1574005664");
            _returnVal1.setDeptOrderBy("DeptOrderBy841591662");
            _returnVal1.setDeptLevel("DeptLevel-1915012715");
            _returnVal1.setDeptLevelDesc("DeptLevelDesc-498668147");
            _returnVal1.setEffectDt("EffectDt-243245429");
            _returnVal1.setLevel("Level-478934315");
            _returnVal1.setSegSegmentNo("SegSegmentNo105154496");
            _returnVal1.setUpperDept("UpperDept-168545135");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getEmployeeByEmpName(java.lang.String  strEmpName )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getEmployeeByEmpName(java.lang.String strEmpName) { 
        LOG.info("Executing operation getEmployeeByEmpName");
        System.out.println(strEmpName);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Employee> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Employee>();
            com.cymmetrik.webservices.hr.Employee _returnVal1 = new com.cymmetrik.webservices.hr.Employee();
            _returnVal1.setCardNo("CardNo1279079900");
            _returnVal1.setCompId("CompId1115675781");
            _returnVal1.setDeptName("DeptName956507376");
            _returnVal1.setDeptNo("DeptNo415167320");
            _returnVal1.setEffectDt("EffectDt1877083486");
            _returnVal1.setEmail("Email-892800960");
            _returnVal1.setEmpName("EmpName-81756585");
            _returnVal1.setEmpNo("EmpNo1640001887");
            _returnVal1.setJobCate("JobCate1971193554");
            _returnVal1.setJobCateDesc("JobCateDesc-1650990160");
            _returnVal1.setJobPlace("JobPlace1434873886");
            _returnVal1.setJobPlaceDesc("JobPlaceDesc-1193971079");
            _returnVal1.setJobStatus(1121686911);
            _returnVal1.setSex("Sex-2118725224");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getAllUnderDeptsNoByCompNoDeptNo(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo )*
     */
    public int getAllUnderDeptsNoByCompNoDeptNo(java.lang.String strCompanyNo,java.lang.String strDeptNo) { 
        LOG.info("Executing operation getAllUnderDeptsNoByCompNoDeptNo");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        try {
            int _return = 1447466629;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getAllUnderEmployeesByCompanyNoDeptNoMainCompY(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo ,)java.lang.String  strCriteria )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getAllUnderEmployeesByCompanyNoDeptNoMainCompY(java.lang.String strCompanyNo,java.lang.String strDeptNo,java.lang.String strCriteria) { 
        LOG.info("Executing operation getAllUnderEmployeesByCompanyNoDeptNoMainCompY");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        System.out.println(strCriteria);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Employee> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Employee>();
            com.cymmetrik.webservices.hr.Employee _returnVal1 = new com.cymmetrik.webservices.hr.Employee();
            _returnVal1.setCardNo("CardNo168958759");
            _returnVal1.setCompId("CompId-412361235");
            _returnVal1.setDeptName("DeptName879050828");
            _returnVal1.setDeptNo("DeptNo463670606");
            _returnVal1.setEffectDt("EffectDt-56670675");
            _returnVal1.setEmail("Email-1881717268");
            _returnVal1.setEmpName("EmpName922223458");
            _returnVal1.setEmpNo("EmpNo802767195");
            _returnVal1.setJobCate("JobCate-1147199647");
            _returnVal1.setJobCateDesc("JobCateDesc98423003");
            _returnVal1.setJobPlace("JobPlace1109984426");
            _returnVal1.setJobPlaceDesc("JobPlaceDesc697677973");
            _returnVal1.setJobStatus(1262491590);
            _returnVal1.setSex("Sex1260586022");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getEmployeesByCompanyNoAndDeptNo(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo ,)boolean  bAll )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getEmployeesByCompanyNoAndDeptNo(java.lang.String strCompanyNo,java.lang.String strDeptNo,boolean bAll) { 
        LOG.info("Executing operation getEmployeesByCompanyNoAndDeptNo");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        System.out.println(bAll);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Employee> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Employee>();
            com.cymmetrik.webservices.hr.Employee _returnVal1 = new com.cymmetrik.webservices.hr.Employee();
            _returnVal1.setCardNo("CardNo2145790042");
            _returnVal1.setCompId("CompId-1576930288");
            _returnVal1.setDeptName("DeptName1996654296");
            _returnVal1.setDeptNo("DeptNo758452240");
            _returnVal1.setEffectDt("EffectDt-1917992819");
            _returnVal1.setEmail("Email1288425580");
            _returnVal1.setEmpName("EmpName1101434153");
            _returnVal1.setEmpNo("EmpNo-539541326");
            _returnVal1.setJobCate("JobCate-1216723986");
            _returnVal1.setJobCateDesc("JobCateDesc1519913086");
            _returnVal1.setJobPlace("JobPlace1484590124");
            _returnVal1.setJobPlaceDesc("JobPlaceDesc613677890");
            _returnVal1.setJobStatus(1831222192);
            _returnVal1.setSex("Sex826785326");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getDeptsNoByCompanyNoAndDeptNo(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo )*
     */
    public int getDeptsNoByCompanyNoAndDeptNo(java.lang.String strCompanyNo,java.lang.String strDeptNo) { 
        LOG.info("Executing operation getDeptsNoByCompanyNoAndDeptNo");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        try {
            int _return = -332413104;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getDepartmentsByCompanyNoAndDeptNo(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Department> getDepartmentsByCompanyNoAndDeptNo(java.lang.String strCompanyNo,java.lang.String strDeptNo) { 
        LOG.info("Executing operation getDepartmentsByCompanyNoAndDeptNo");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Department> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Department>();
            com.cymmetrik.webservices.hr.Department _returnVal1 = new com.cymmetrik.webservices.hr.Department();
            _returnVal1.setDeptDeputyMgr1("DeptDeputyMgr11008389016");
            _returnVal1.setDeptDeputyMgr2("DeptDeputyMgr21967955137");
            _returnVal1.setDeptMgr("DeptMgr-107795038");
            _returnVal1.setDeptMgrName("DeptMgrName1438777936");
            _returnVal1.setDeptName("DeptName-2093791762");
            _returnVal1.setDeptNo("DeptNo272171070");
            _returnVal1.setDeptOrderBy("DeptOrderBy-184947045");
            _returnVal1.setDeptLevel("DeptLevel-1999884087");
            _returnVal1.setDeptLevelDesc("DeptLevelDesc-363478809");
            _returnVal1.setEffectDt("EffectDt247361320");
            _returnVal1.setLevel("Level338389023");
            _returnVal1.setSegSegmentNo("SegSegmentNo-922055924");
            _returnVal1.setUpperDept("UpperDept1753689042");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getAllCompany(*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Company> getAllCompany() { 
        LOG.info("Executing operation getAllCompany");
        try {
            java.util.List<com.cymmetrik.webservices.hr.Company> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Company>();
            com.cymmetrik.webservices.hr.Company _returnVal1 = new com.cymmetrik.webservices.hr.Company();
            _returnVal1.setAbbreviatedName("AbbreviatedName-1157450408");
            _returnVal1.setAddress("Address-753903016");
            _returnVal1.setAddressInEng("AddressInEng-1031824331");
            _returnVal1.setFax("Fax-1608153809");
            _returnVal1.setName("Name1874292656");
            _returnVal1.setNameInEng("NameInEng248029884");
            _returnVal1.setNation("Nation-1377231492");
            _returnVal1.setSegSegmentNo("SegSegmentNo1797698929");
            _returnVal1.setTel("Tel1813596563");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getEmployeeByLikeNameLoginId(java.lang.String  strData )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getEmployeeByLikeNameLoginId(java.lang.String strData) { 
        LOG.info("Executing operation getEmployeeByLikeNameLoginId");
        System.out.println(strData);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Employee> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Employee>();
            com.cymmetrik.webservices.hr.Employee _returnVal1 = new com.cymmetrik.webservices.hr.Employee();
            _returnVal1.setCardNo("CardNo-646013331");
            _returnVal1.setCompId("CompId-665406774");
            _returnVal1.setDeptName("DeptName874762757");
            _returnVal1.setDeptNo("DeptNo463543702");
            _returnVal1.setEffectDt("EffectDt1646513889");
            _returnVal1.setEmail("Email-912827249");
            _returnVal1.setEmpName("EmpName1856441490");
            _returnVal1.setEmpNo("EmpNo-556143241");
            _returnVal1.setJobCate("JobCate-515857211");
            _returnVal1.setJobCateDesc("JobCateDesc-1960070446");
            _returnVal1.setJobPlace("JobPlace1003672194");
            _returnVal1.setJobPlaceDesc("JobPlaceDesc-762714803");
            _returnVal1.setJobStatus(1245418782);
            _returnVal1.setSex("Sex-1246216823");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cymmetrik.webservices.hr.IHRService#getAllEmployeesByCompanyNoAndDeptNo(java.lang.String  strCompanyNo ,)java.lang.String  strDeptNo ,)boolean  bAll )*
     */
    public java.util.List<com.cymmetrik.webservices.hr.Employee> getAllEmployeesByCompanyNoAndDeptNo(java.lang.String strCompanyNo,java.lang.String strDeptNo,boolean bAll) { 
        LOG.info("Executing operation getAllEmployeesByCompanyNoAndDeptNo");
        System.out.println(strCompanyNo);
        System.out.println(strDeptNo);
        System.out.println(bAll);
        try {
            java.util.List<com.cymmetrik.webservices.hr.Employee> _return = new java.util.ArrayList<com.cymmetrik.webservices.hr.Employee>();
            com.cymmetrik.webservices.hr.Employee _returnVal1 = new com.cymmetrik.webservices.hr.Employee();
            _returnVal1.setCardNo("CardNo618455233");
            _returnVal1.setCompId("CompId-91496959");
            _returnVal1.setDeptName("DeptName-803611471");
            _returnVal1.setDeptNo("DeptNo-19628502");
            _returnVal1.setEffectDt("EffectDt-1421848635");
            _returnVal1.setEmail("Email697963260");
            _returnVal1.setEmpName("EmpName1342084517");
            _returnVal1.setEmpNo("EmpNo-372736383");
            _returnVal1.setJobCate("JobCate1530256333");
            _returnVal1.setJobCateDesc("JobCateDesc-2044592351");
            _returnVal1.setJobPlace("JobPlace-2133654682");
            _returnVal1.setJobPlaceDesc("JobPlaceDesc-191629116");
            _returnVal1.setJobStatus(-1338905236);
            _returnVal1.setSex("Sex1631884541");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
